### ISSUE TITLE
The `:host` parameter should not be set for `unix://` connections.

### ISSUE THREAD

**Issue by fcecagno** [upserve/docker-api#583]
Hi, having a weird issue using a very simple code with docker gem:

```
$ DOCKER_URL=unix:///var/run/docker.sock irb
irb(main):001:0> require 'docker'
=> true
irb(main):002:0> Docker::Container.all(:all => true)
Traceback (most recent call last):
       11: from /usr/bin/irb:23:in `<main>'
       10: from /usr/bin/irb:23:in `load'
        9: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        8: from (irb):2
        7: from /var/lib/gems/2.7.0/gems/docker-api-2.2.0/lib/docker/container.rb:343:in `all'
        6: from /var/lib/gems/2.7.0/gems/docker-api-2.2.0/lib/docker/connection.rb:109:in `block (2 levels) in <class:Connection>'
        5: from /var/lib/gems/2.7.0/gems/docker-api-2.2.0/lib/docker/connection.rb:45:in `request'
        4: from /var/lib/gems/2.7.0/gems/docker-api-2.2.0/lib/docker/connection.rb:35:in `resource'
        3: from /var/lib/gems/2.7.0/gems/excon-0.92.4/lib/excon.rb:142:in `new'
        2: from /var/lib/gems/2.7.0/gems/excon-0.92.4/lib/excon.rb:142:in `new'
        1: from /var/lib/gems/2.7.0/gems/excon-0.92.4/lib/excon/connection.rb:93:in `initialize'
ArgumentError (The `:host` parameter should not be set for `unix://` connections.)
When supplying a `unix://` URI, it should start with `unix:/` or `unix:///`.
```

I'm most certainly it's not an issue in the library itself because it used to work for a long time.
Do you have any idea why I'd hit this?

**Comment by fcecagno** [comment]
Related to https://github.com/excon/excon/issues/805
Update dependency `excon` gem from 0.92.4 to 0.99.0 seems to fix the issue, although it doesn't explain why this issue appeared from nowhere without any changes in the deployment.
I hope it helps others to track down the same issue.
