### ISSUE TITLE
cannot use excon 0.111.0 - FreezeError

### ISSUE THREAD

**Issue by b-dean** [upserve/docker-api#587]
https://github.com/excon/excon/compare/v0.110.0...v0.111.0

using this Gemfile
```
source 'https://rubygems.org'

gem 'docker-api', '~> 2.2'
```
installs:
``` 
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching multi_json 1.15.0
Fetching excon 0.111.0
Installing multi_json 1.15.0
Installing excon 0.111.0
Fetching docker-api 2.2.0
Installing docker-api 2.2.0
```

then just doing `require 'docker'` gives a `FrozenError`

```
$ bundle exec ruby -e 'require "docker"'
/home/foo/.rvm/gems/ruby-3.2.2@docker-api/gems/docker-api-2.2.0/lib/excon/middlewares/hijack.rb:2:in `<module:Excon>': can't modify frozen Array: [:allow_unstubbed_requests, :body, :chunk_size, :debug_request, :debug_response, :dns_timeouts, :headers, :instrumentor, :logger, :method, :middlewares, :password, :path, :persistent, :pipeline, :query, :read_timeout, :request_block, :resolv_resolver, :response_block, :stubs, :timeout, :user, :versions, :write_timeout] (FrozenError)
	from /home/foo/.rvm/gems/ruby-3.2.2@docker-api/gems/docker-api-2.2.0/lib/excon/middlewares/hijack.rb:1:in `<top (required)>'
	from <internal:/home/foo/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/foo/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/foo/.rvm/gems/ruby-3.2.2@docker-api/gems/docker-api-2.2.0/lib/docker.rb:14:in `<top (required)>'
	from <internal:/home/foo/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/foo/.rvm/rubies/ruby-3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from -e:1:in `<main>'
```

If I restrict excon in the gemfile it's fine
```
gem 'excon', '!= 0.111.0'
```

**Comment by b-dean** [comment]
duplicate of #586
